jobster/jobster/urls.py
from django.conf.urls import include,url
from django.contrib import admin



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("submitresume.urls")),


]

jobster/submitresume/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login

app_name='submitresume'
urlpatterns = [
    url(r'^register$',views.userformview.as_view(), name ='register'),
    url(r'^login/$',views.login_user,name='login' ),
    url(r'^$',views.resume_form.as_view(), name ='submit-resume'),
    url(r'^index/(?P<resume_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^selected/(?P<resume_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^index/(?P<resume_id>[0-9]+)/select/$', views.select_resume, name='select'),
    url(r'^selected/$', views.selected_list, name='selected_list'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^index/$', views.index, name='index'),


]

jobster/submitresume/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Resume(models.Model):
    Name=models.CharField(max_length=100)
    Age=models.PositiveIntegerField(max_length=2)
    Qualification=models.CharField(max_length=200)
    Email=models.EmailField(max_length=150)
    Phone_number = models.PositiveIntegerField(max_length=9)
    About_Me=models.TextField(max_length=1000)
    Skills=models.CharField(max_length=500)
    is_selected = models.BooleanField(default=False)

    def __str__(self):
        return(str(self.pk)+" "+self.Name+" "+self.Qualification)

    def get_absolute_url(self):
        return reverse('submitresume:submit-resume')

jobster/submitresume/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Resume

class Recruiter_register(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)


    class Meta:
        model = User
        fields = ['username','email','password']

class Recruiter_login(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)


    class Meta:
        model = User
        fields = ['username','password']


class resume_submit(forms.ModelForm):
    Age = forms.CharField(max_length=2, min_length=2)
    Phone_number=forms.CharField(max_length=12, min_length=10)
    class Meta:
        model = Resume
        fields = ['Name','Age', 'Qualification','Email','Phone_number','About_Me','Skills']

jobster/submitresume/views.py
from .models import Resume
from django.views.generic.edit import CreateView
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate,login,logout
from django.views.generic import View
from .forms import Recruiter_register,resume_submit
from django.http import JsonResponse





class submitresume(CreateView):
    model = Resume

    fields = ['Name','Age','Qualification','Email','Phone_number','About_Me','Skills']


class userformview(View):
    form_class=Recruiter_register
    template_name='submitresume/login.html'

    # displays blank form
    def get(self,request):
        form=self.form_class(None)
        return render(request,self.template_name,{'form':form})


    #submits the filled form
    def post(self, request):
        form=self.form_class(request.POST)

        if form.is_valid():

            user=form.save(commit=False)

            #clean normalized data

            username=form.cleaned_data['username']
            password=form.cleaned_data['password']
            user.set_password(password)
            user.save()

            #return user object if credentials are correct

            user = authenticate(username=username,password=password)

            if user is not None:
                if user.is_active:
                    login(request,user)
                    return redirect('submitresume:login')


        return render(request, self.template_name, {'form': form})


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                resumes = Resume.objects.all()
                return redirect('submitresume:index')
            else:
                return render(request, 'submitresume/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'submitresume/login.html', {'error_message': 'Invalid login'})
    elif request.method == "get":
        return redirect('submitresume:index')
    return render(request, 'submitresume/login.html')


def detail(request, resume_id):
    if not request.user.is_authenticated():
        return redirect('submitresume:login')
    else:
        user = request.user
        resume = get_object_or_404(Resume, pk=resume_id)
        return render(request, 'submitresume/detail.html', {'resume': resume, 'user': user})




def logout_user(request):
    logout(request)
    form = Recruiter_register(request.POST or None)
    context = {
        "form": form,
    }
    return redirect('submitresume:login')

def index(request):
    if not request.user.is_authenticated():
        return redirect('submitresume:login')
    else:
        resumes = Resume.objects.all()
        return render(request, 'submitresume/index.html', {'resumes': resumes})





def select_resume(request, resume_id):
    resume = get_object_or_404(Resume, pk=resume_id)
    try:
        if resume.is_selected:
            resume.is_selected = False
        else:
            resume.is_selected = True
        resume.save()
    except (KeyError, resume.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return redirect('submitresume:detail',resume_id)


def selected_list(request):
    if not request.user.is_authenticated():
        return redirect('submitresume:login')
    else:
        resumes = Resume.objects.filter(is_selected=True)
        return render(request, 'submitresume/index.html', {'resumes': resumes})


class resume_form(View):
    model = Resume
    form_class=resume_submit
    template_name='submitresume/submit_resume.html'
    template_success='submitresume/Success.html'

    # displays blank form
    def get(self,request):
        form=self.form_class(None)
        return render(request,self.template_name,{'form':form})


    #submits the filled form
    def post(self, request):
        form=self.form_class(request.POST)

        if form.is_valid():

            Resume=form.save(commit=False)
            resume = Resume
            #clean normalized data

            resume.Name=form.cleaned_data['Name']
            resume.Age=form.cleaned_data['Age']
            resume.Qualification=form.cleaned_data['Qualification']
            resume.Email = form.cleaned_data['Email']
            resume.Phone_number=form.cleaned_data['Phone_number']
            resume.About_Me=form.cleaned_data['About_Me']
            resume.Skills=form.cleaned_data['Skills']


            resume.save()
            return render(request, self.template_success, {'form': form})
        else:

            return render(request, self.template_name, {'form': form})

jobster/submitresume/templates/submitresume/Success.html
{% extends 'submitresume/baseloggedout.html' %}
{% block body %}
<h3>Resume uploaded successfully</h3>
{% endblock %}

jobster/submitresume/templates/submitresume/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>{% block title %}jobster{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>


</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">

        <div class="container-fluid">

            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                {% load staticfiles %}
                <link rel="stylesheet" href="{% static "submitresume/index.css"%}">
                <a class="navbar-brand" href="{% url 'submitresume:index' %}">Jobster</a>
                 <ul class="nav navbar-nav">
                    <li><a href={% url 'submitresume:index' %}>all Resumes</a></li>
                    <li><a href={% url 'submitresume:selected_list' %}>Selected resumes</a></li>
                </ul>

            </div>

            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">


                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'submitresume:logout_user' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                        </a>
                    </li>
                </ul>
            </div>

        </div>

</nav>

{% block body %}
{% endblock %}
</body>
</html>

jobster/submitresume/templates/submitresume/baseloggedout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}jobster{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>


</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand" href="{% url 'submitresume:submit-resume' %}">Jobster</a>

        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">


            <ul class="nav navbar-nav navbar-right">

                <li>
                    <a href="{% url 'submitresume:login' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Login
                    </a>
                </li>

            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

jobster/submitresume/templates/submitresume/detail.html
{% extends 'submitresume/base.html' %}
{% block body %}
<div class="jumbotron">
    <div id="content"></div>
        <h2 class="display-3">{{resume.Name}}</h2>
        <p>{{resume.Age}}</p>
        <p>{{resume.Qualification}}</p>
        <p>{{resume.Email}}</p>
        <p>{{Phone_number}}</p>
        <p class="lead">{{resume.About_Me}}</p>
        <p>{{resume.Skills}}</p>
    {% if resume.is_selected %}<p> <em>Selected</em></p>{%endif%}

        <a class="btn btn-primary btn-lg" href="{% url 'submitresume:select' resume.id %}" role="button">{% if resume.is_selected %}Reject{% else %}Select{% endif %}</a>


    </div>
</div>



{% endblock %}

jobster/submitresume/templates/submitresume/index.html
{% extends 'submitresume/base.html' %}


{% block body %}
{% load staticfiles %}
<div id="list-view">
<ul>
    <div class="listitem">
 {% for resume in resumes %}

    <li>
        <a href={{resume.id}}>

                <h3>{{resume.Name}}</h3>
                <p>{{resume.Age}}</p>
                <p>{{resume.Skills}}</p>
            {% if  resume.is_selected %}
        <img src="{% static "submitresume/tick.png" %}" alt="tick" height="42" width="42" align="right">
            {% endif %}
        </a>

    </li>

    {%endfor%}
     </div>
</ul>

</div>

{% endblock %}

jobster/submitresume/templates/submitresume/login.html
{% extends 'submitresume/baseloggedout.html' %}

{% block body %}
<div class="container">
    <form class="form-signin" action="" method="post" enctype="multipart/form-data">
        <h2 class="form-signin-heading">Please sign in</h2>
        {% csrf_token %}
        {% if error_message %}
        <span>{{error_message}}</span>
        {% endif %}
              <div>
             <label>Username:</label><br>
                <input id="id_username" class="input-block-level" maxlength="30" name="username" type="text"><br>
              <label>Password:</label><br>
                <input id="id_password" class="input-block-level" maxlength="30" name="password" type="password"><br>
                <br>

          <button class="btn btn-large btn-primary" type="submit">submit</button>

    </form>
</div>


{% endblock %}

jobster/submitresume/templates/submitresume/resume_form.html
{% extends 'submitresume/baseloggedout.html' %}

{% block body %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
    <span>{{ field.errors }}</span>
    <label>{{field.label_tag}}</label>
    <div>
        {{field}}
    </div>
    {% endfor %}

    <button type="submit">submit</button>

</form>

{% endblock %}

jobster/submitresume/templates/submitresume/selected_resume.html
{% extends 'submitresume/base.html' %}


{% block body %}
{% for resume in resumes %}
{% if resume.is_selected %}

<div id="list-view">
<ul>


    <li>
        <a href={{resume.id}}>
            <div class="listitem">
                <h3>{{resume.Name}}</h3>
                <p>{{resume.Age}}</p>
            </div>
        </a>

    </li>

</ul>

</div>
{% endif %}
{%endfor%}
{% endblock %}

jobster/submitresume/templates/submitresume/selectedresume.html
{% extends 'submitresume/base.html' %}


{% block body %}
{% for resume in selectedresumes %}

<div id="list-view">
<ul>


    <li>
        <a href={{resume.id}}>
            <div class="listitem">
                <h3>{{resume.Name}}</h3>
                <p>{{resume.Age}}</p>
            </div>
        </a>

    </li>

</ul>

</div>
{%endfor%}
{% endblock %}

jobster/submitresume/templates/submitresume/submit_resume.html
{% extends 'submitresume/baseloggedout.html' %}

        {% block body %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <form action="" method="post" enctype="multipart/form-data">
            <h2 class="form-heading">Submit your details below</h2>
            {% csrf_token %}
            {% for field in form %}

            <label>{{field.label_tag}}</label>
            <span>{{ field.errors }}</span>
            <div>
                {{field}}
            </div>
            {% endfor %}
            <br>
            <button class="btn btn-large btn-primary" type="submit">submit</button>

        </form>
    </div>
</div>
        {% endblock %}